### ISSUE TITLE
replace md5_file with something faster?

### ISSUE THREAD

**Issue by sunnysideup** [heyday/silverstripe-hashpath#10]
Would it be an idea to replace md5_file with something faster ... e.g. 

```php

filemtime($filePath);

```

I am not sure if there are situations where a file can be changed at exactly the same time but still be different, but I reckon it would speed things up a fair bit.

**Comment by camspiers** [comment]
It think this would defeat the purpose of the module. The time the file changes doesn't reflect the contents of the file as timestamps can change without contents changing. This would bust the client-side caches for users of your app for no reason. If you know of a faster but low-ish collision hashing algorithm that would be awesome.

**Comment by sunnysideup** [comment]
Totally agree with the above.  

You could also cache the hash path so that you would need to do a flush to clear them. 

I may give it some further thought.
