### ISSUE TITLE
Incompatible with 4.1 public webroot folder

### ISSUE THREAD

**Issue by thats4shaw** [heyday/silverstripe-hashpath#12]
The introduction of the new public webroot folder in SilverStripe 4.1 breaks the $HashPath functionality.

I'll aim to try and supply a pull request once I get a spare time to figure out a fix.

**Comment by thats4shaw** [comment]
Bit more digging this morning.

When you expose your theme files publicly they are actually symlinks so the rewrite rules this module requires in the .htaccess rules need some tweaking.

```
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-l
RewriteRule ^(.+)\.(v[A-Za-z0-9]+)\.(js|css|png|jpg|gif)$ $1.$3 [L]
```

From what I can tell the following also needs to be added `Options +FollowSymlinks`.  However this maybe complicated by the AllowOverride settings of the vhost.

**Comment by wernerkrauss** [comment]
It should use resourceUrlLoader to be compatible with 4.1+ public webroot
